mkdir build\dynamic
mkdir build\dynamic\renderergl2
cscript.exe glsl_stringify.vbs code\renderergl2\glsl\bokeh_fp.glsl build\dynamic\renderergl2\bokeh_fp.c
cscript.exe glsl_stringify.vbs code\renderergl2\glsl\bokeh_vp.glsl build\dynamic\renderergl2\bokeh_vp.c
cscript.exe glsl_stringify.vbs code\renderergl2\glsl\calclevels4x_fp.glsl build\dynamic\renderergl2\calclevels4x_fp.c
cscript.exe glsl_stringify.vbs code\renderergl2\glsl\calclevels4x_vp.glsl build\dynamic\renderergl2\calclevels4x_vp.c
cscript.exe glsl_stringify.vbs code\renderergl2\glsl\depthblur_fp.glsl build\dynamic\renderergl2\depthblur_fp.c
cscript.exe glsl_stringify.vbs code\renderergl2\glsl\depthblur_vp.glsl build\dynamic\renderergl2\depthblur_vp.c
cscript.exe glsl_stringify.vbs code\renderergl2\glsl\dlight_fp.glsl build\dynamic\renderergl2\dlight_fp.c
cscript.exe glsl_stringify.vbs code\renderergl2\glsl\dlight_vp.glsl build\dynamic\renderergl2\dlight_vp.c
cscript.exe glsl_stringify.vbs code\renderergl2\glsl\down4x_fp.glsl build\dynamic\renderergl2\down4x_fp.c
cscript.exe glsl_stringify.vbs code\renderergl2\glsl\down4x_vp.glsl build\dynamic\renderergl2\down4x_vp.c
cscript.exe glsl_stringify.vbs code\renderergl2\glsl\fogpass_fp.glsl build\dynamic\renderergl2\fogpass_fp.c
cscript.exe glsl_stringify.vbs code\renderergl2\glsl\fogpass_vp.glsl build\dynamic\renderergl2\fogpass_vp.c
cscript.exe glsl_stringify.vbs code\renderergl2\glsl\generic_fp.glsl build\dynamic\renderergl2\generic_fp.c
cscript.exe glsl_stringify.vbs code\renderergl2\glsl\generic_vp.glsl build\dynamic\renderergl2\generic_vp.c
cscript.exe glsl_stringify.vbs code\renderergl2\glsl\lightall_fp.glsl build\dynamic\renderergl2\lightall_fp.c
cscript.exe glsl_stringify.vbs code\renderergl2\glsl\lightall_vp.glsl build\dynamic\renderergl2\lightall_vp.c
cscript.exe glsl_stringify.vbs code\renderergl2\glsl\pshadow_fp.glsl build\dynamic\renderergl2\pshadow_fp.c
cscript.exe glsl_stringify.vbs code\renderergl2\glsl\pshadow_vp.glsl build\dynamic\renderergl2\pshadow_vp.c
cscript.exe glsl_stringify.vbs code\renderergl2\glsl\shadowfill_fp.glsl build\dynamic\renderergl2\shadowfill_fp.c
cscript.exe glsl_stringify.vbs code\renderergl2\glsl\shadowfill_vp.glsl build\dynamic\renderergl2\shadowfill_vp.c
cscript.exe glsl_stringify.vbs code\renderergl2\glsl\shadowmask_fp.glsl build\dynamic\renderergl2\shadowmask_fp.c
cscript.exe glsl_stringify.vbs code\renderergl2\glsl\shadowmask_vp.glsl build\dynamic\renderergl2\shadowmask_vp.c
cscript.exe glsl_stringify.vbs code\renderergl2\glsl\ssao_fp.glsl build\dynamic\renderergl2\ssao_fp.c
cscript.exe glsl_stringify.vbs code\renderergl2\glsl\ssao_vp.glsl build\dynamic\renderergl2\ssao_vp.c
cscript.exe glsl_stringify.vbs code\renderergl2\glsl\texturecolor_fp.glsl build\dynamic\renderergl2\texturecolor_fp.c
cscript.exe glsl_stringify.vbs code\renderergl2\glsl\texturecolor_vp.glsl build\dynamic\renderergl2\texturecolor_vp.c
cscript.exe glsl_stringify.vbs code\renderergl2\glsl\tonemap_fp.glsl build\dynamic\renderergl2\tonemap_fp.c
cscript.exe glsl_stringify.vbs code\renderergl2\glsl\tonemap_vp.glsl build\dynamic\renderergl2\tonemap_vp.c
